### ISSUE TITLE
ne fonctionne plus avec Safari v11

### ISSUE THREAD

**Issue by vjeantet** [Grominet/aT-My-Freebox#2]
il ne se passe rien quand on click sur le menu du menu contextuel

**Comment by Grominet** [comment]
Fonctionnes chez moi, donc pas un problème de Safari
Est-ce que les paramètres dans les préférences de l'extension sont bien renseigné?
Tenter de supprimer/recréer les autorisations dans le FreeboxOs.

**Comment by vjeantet** [comment]
c'est ok pour moi, je ne sais pas ce qui a mal fonctionné
