### ISSUE TITLE
Mojave / Safari 12

### ISSUE THREAD

**Issue by vjeantet** [Grominet/aT-My-Freebox#3]
Hello @Grominet , at my Freebox est désactivée dans safari 12.

Comment faire pour le garder opérationel ?

**Comment by Grominet** [comment]
Hello,
malheureusement c'est pas prévu de sitôt...
1.Apple a complètement changé le principe, il faudrait que je dev une "vraie app", mais "fantôme" pour y intégrer l'extension qui ne peut plus vivre seule
2.Refaire le code js pour le passer en partie en swift (alors que la base n'est déjà pas de moi, mais de download at my freebox, l'extension chrome)
3.Avoir un compte Apple Dev, peut-être qu'un jour je relancerais mes apps... mais pas prévu
4.Avoir Mojave/Safari 12 pour tester, ce que je ne peux pas avec mon vénérable MBP2011...

Donc si un dev perdu par ici est motivé, il est le bienvenue pour prendre le relai!
Sinon, voir les autres browser...
A une prochaine,
